all:
  children:
    spines:
      hosts:
        spine1:
          ansible_host: clab-phase1-frr-spine1
        spine2:
          ansible_host: clab-phase1-frr-spine2
    leafs:
      hosts:
        leaf1:
          ansible_host: clab-phase1-frr-leaf1
        leaf2:
          ansible_host: clab-phase1-frr-leaf2
  vars:
    ansible_user: root
    ansible_connection: docker  # SSHではなく直接dockerコマンド経由で操作
    # ↓ここを追加！一時フォルダを /tmp に固定する
    ansible_remote_tmp: /tmp